#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $MAFIA_REPO == "mafiabot" ]]
    then
        echo "https://github.com/SaliraVoda/MAFIA-USERBOT"
    elif [[ $MAFIA_REPO == "MAFIABOT" ]]
    then
        echo "https://github.com/SaliraVoda/MAFIA-USERBOT"
    elif [[ $MAFIA_REPO =~ $regex ]]
    then
        if [[ $MAFIA_REPO_BRANCH ]]
        then
            echo "${MAFIA_REPO}/archive/${MAFIA_REPO_BRANCH}.zip"
        else
            echo "${MAFIA_REPO}/archive/master.zip"
        fi
    else
        echo "https://github.com/SaliraVoda/MAFIA-USERBOT"
    fi
}


_set_bot () {
    local zippath
    zippath="mafiabot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    MAFIAPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $MAFIAPATH
    echo "    Starting MafiaBot    "
    echo "
                          ╔═╦═╦══╦══╦══╦══╦══╦═╦══╗
                          ║║║║║╔╗║═╦╩║║╣╔╗║╔╗║║╠╗╔╝
                          ║║║║║╠╣║╔╝╔║║╣╠╣║╔╗║║║║║
                          ╚╩═╩╩╝╚╩╝─╚══╩╝╚╩══╩═╝╚╝
    "

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
